name: publish_for_int
run-name: int imageresize build and publish
on:
  workflow_run:
    workflows: [Bump Version]
    types:
      - completed
jobs:
  publish:
    runs-on: ubuntu-latest
    environment:
      name: int
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    steps:
      - uses: actions/checkout@v3
        name: Check out code

      - uses: mr-smithers-excellent/docker-build-push@v6
        name: Build & push Docker image
        with:
          image: cblair/imageresize
          tags: int #, int-${{ github.event.release.tag_name }}
          registry: docker.io
          dockerfile: Dockerfile
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
          buildArgs: NEXT_PUBLIC_STRIPE_PUBLISHABLE_KEY=${{secrets.NEXT_PUBLIC_STRIPE_PUBLISHABLE_KEY}}, NEXT_PUBLIC_STRIPE_SECRET_KEY=${{secrets.NEXT_PUBLIC_STRIPE_SECRET_KEY}}, NEXT_PUBLIC_PATIENT_PORTAL_ACCOUNT_CONFIRM_URL=${{vars.NEXT_PUBLIC_PATIENT_PORTAL_ACCOUNT_CONFIRM_URL}}
